name: Generate Pull Request Description

on:
  pull_request:  # Triggers the workflow on pull request events
    types: [opened, synchronize, reopened]  # You can adjust these if needed

jobs:
  update-pull-request-description:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # No changes needed here

    - name: Generate Pull Request Description
      id: pr-description
      uses: octue/generate-pull-request-description@1.0.0.beta-2
      with:
        pull_request_url: ${{ github.event.pull_request.url }}  # No changes needed
        api_token: ${{ secrets.GITHUB_TOKEN }}  # Ensure GITHUB_TOKEN is set or replace with your custom token

    - name: Update Pull Request Body
      uses: riskledger/update-pr-description@v2
      with:
        body: ${{ steps.pr-description.outputs.pull_request_description }}  # No changes needed
        token: ${{ secrets.GITHUB_TOKEN }}  # Ensure GITHUB_TOKEN is set or replace with your custom token
